### ISSUE TITLE
OSX Yosemite Capatability

### ISSUE THREAD

**Issue by matthewjamesr** [spolu/breach_core#182] opened 2014-07-25 09:07 UTC
Hello gents,

Just curious as I am wanting I install the new OSX beta, has anyone been successfully wen using breach on it? Thanks!

**Comment by brayniverse** [comment] 2014-07-25 10:41
I've used it on both Mavericks and Yosemite and they work the same.

**Comment by charleshaa** [comment] 2014-07-25 11:13
I have it on Yosemite and as of now I only managed to display Google properly. Pretty much any other site I tested breaks as soon as I scroll...

**Comment by yperson** [comment] 2014-07-25 13:54
On Yosemite, as soon as you wanna scroll, the whole page becomes white.

**Comment by brayniverse** [comment] 2014-07-25 13:55
Does anybody know why this is happening?

**Comment by spolu** [comment] 2014-07-25 14:00
I would need to investigate this on a OSX 10.10 machine. My intuition tells me this is related to exo_browser's use of WebContents HasShown method... But this is a long shot

**Comment by brayniverse** [comment] 2014-07-25 14:05
Bummer, I was hoping it was something I could help fix. Sorry but I don't have enough experience with C++ to help.

**Comment by spolu** [comment] 2014-07-27 16:31
Closing as duplicate of #116

**Closed as completed by spolu** 2014-07-27 16:31 UTC
