### ISSUE TITLE
Tab doesn't open after search when clicking on it 

### ISSUE THREAD

**Issue by bennybennet** [spolu/breach_core#113] opened 2014-07-12 14:40 UTC
First of all thanks for this great project.

When i have some tabs open and using the search/adress input to search through tabs, and then click on one tab it doesn't open the tab. Instead it removes my input and just displays the tab as before.

Steps to reproduce:
- Open Breach
- Open 2, 3 or more Tabs
- Search Tab
- Click On a Tab

**Comment by spolu** [comment] 2014-07-12 17:14
Hi! This is a duplicate of https://github.com/breach/mod_strip/issues/21 which has been fixed but has not been package in a new version of mod_strip yet.

Thanks for the bug report!

**Closed as completed by spolu** 2014-07-12 17:14 UTC

**Comment by bennybennet** [comment] 2014-07-12 17:28
Hi
Thanks for the fix and sorry for the duplicate issue. :+1:

**Comment by spolu** [comment] 2014-07-12 18:37
No worry ;-)
