### ISSUE TITLE
mod_strip and dev tools all white on Mac OS X 10.10

### ISSUE THREAD

**Issue by octalmage** [spolu/breach_core#94] opened 2014-07-11 10:44 UTC
Just downloaded and launched Breach and both the url/tab bar(mod_strip) and dev tools are completly white: 

![](https://i.cloudup.com/zMMdCDSv0C.png)
(dev tools open)

mod_strip output: 

```
OPTION: --no-chrome
[2014-07-11T10:16:23.272Z] HTTP Server started on `http://127.0.0.1:57220`
EXPOSED: init
EXPOSED: kill
EXPOSED: init
EXPOSED: kill
EXPOSED: box_find_in_page
EXPOSED: box_focus
EXPOSED: box_select_all
EXPOSED: context_menu_builder
[2014-07-11T10:16:28.271Z] [tabs] tabs_show __NEW_TAB_ID__
```

I figure it's because I'm using the Mac OS X Yosemite beta, but I didn't see this issue reported. 

Any ideas?

**Comment by octalmage** [comment] 2014-07-11 10:47
Output when running Breach from command line:

```
2014-07-11 05:46:23.755 Breach[16965:404897] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
[2014-07-11T10:46:23.972Z] [index] Breach v0.3.20-alpha.5 Starting...
[2014-07-11T10:46:24.867Z] [core_ui] HTTP Server started on `http://127.0.0.1:57766/`
[16965:1291:0711/054624:49760428944039:INFO:exo_session.cc(88)] VisitedLink Init: 1
[16965:1291:0711/054624:49760429018837:INFO:devtools_delegate.cc(132)] ExoBrowserDevToolsDelegate Constructor
[16965:1291:0711/054624:49760429058700:INFO:content_browser_client.cc(190)] Register Session
[16965:24579:0711/054624:49760507433756:INFO:exo_browser_wrap.cc(331)] ExoBrowserWrap CreateCallback
[16965:24579:0711/054624:49760507928453:INFO:exo_session_wrap.cc(268)] CreateCallback ExoSessionWrap
[16965:1291:0711/054625:49760512671492:INFO:exo_frame.cc(78)] ExoFrame Constructor (web_contents created) [0x7a3a5a00]
[16965:24579:0711/054625:49760518847463:INFO:exo_frame_wrap.cc(322)] CreateCallback ExoFrameWrap
[16965:1291:0711/054625:49760520142844:INFO:exo_frame.cc(106)] ExoFrame SetType [0x7989b220]: 2
[16965:1291:0711/054625:49760520179597:INFO:exo_frame.cc(97)] ExoFrame SetParent [0x7a3a5a00]: 0x799923e0
[2014-07-11T10:46:25.075Z] [auto_updater] Breach v0.3.20-alpha.5 is up to date!
[16965:26115:0711/054625:49760703945557:INFO:exo_session_cookie_store.cc(31)] Load
[16965:26115:0711/054625:49760704010662:INFO:exo_session_cookie_store.cc(46)] LoadCookiesForKey: ''
[16965:24579:0711/054625:49760818639088:INFO:exo_session_wrap.cc(679)] CookiesLoad [0]
[2014-07-11T10:46:25.306Z] [core_cookies] load_for_key: null
[16965:24579:0711/054625:49760819162840:INFO:exo_session_wrap.cc(646)] CookiesLoadForKey:  [1]
[2014-07-11T10:46:25.307Z] [core_cookies] load_for_key:
[2014-07-11T10:46:25.309Z] [core_cookies] loaded 0 cookies
[16965:24579:0711/054625:49760821450622:INFO:exo_session_wrap.cc(606)] CookiesLoadForKeyCallback [1]
[16965:24579:0711/054625:49760821491382:INFO:exo_session_wrap.cc(620)] RETURNED: 0
[2014-07-11T10:46:25.312Z] [core_cookies] loaded 0 cookies
[16965:24579:0711/054625:49760824983981:INFO:exo_session_wrap.cc(606)] CookiesLoadForKeyCallback [0]
[16965:24579:0711/054625:49760825014476:INFO:exo_session_wrap.cc(620)] RETURNED: 0
npm WARN package.json mod_strip@0.2.8-alpha.5 No description
npm WARN package.json mod_strip@0.2.8-alpha.5 No repository field.
npm WARN package.json mod_strip@0.2.8-alpha.5 No README data
npm WARN package.json mod_stats@0.1.4-alpha.5 No description
npm WARN package.json mod_stats@0.1.4-alpha.5 No repository field.
npm WARN package.json mod_stats@0.1.4-alpha.5 No README data
[2014-07-11T10:46:25.829Z] [module_manager] `run_module`: mod_stats [github:breach/mod_stats#v0.1.4-alpha.5]
[2014-07-11T10:46:25.875Z] [core_ui] HANDSHAKE: splash
[2014-07-11T10:46:25.901Z] [core_ui] HANDSHAKE: modules
[2014-07-11T10:46:25.975Z] [module_manager] `run_module`: mod_strip [github:breach/mod_strip#v0.2.8-alpha.5]
[2014-07-11T10:46:25.990Z] [index] Startup Complete
[16965:1291:0711/054626:49762094393815:INFO:exo_frame.cc(78)] ExoFrame Constructor (web_contents created) [0x7ab72400]
[16965:1291:0711/054626:49762096568917:INFO:exo_frame.cc(78)] ExoFrame Constructor (web_contents created) [0x7a39d600]
[16965:24579:0711/054626:49762096858741:INFO:exo_frame_wrap.cc(322)] CreateCallback ExoFrameWrap
[16965:1291:0711/054626:49762109129531:INFO:exo_frame.cc(106)] ExoFrame SetType [0x79968dc0]: 1
[16965:1291:0711/054626:49762109208626:INFO:exo_frame.cc(97)] ExoFrame SetParent [0x7ab72400]: 0x799923e0
[16965:1291:0711/054626:49762109339200:INFO:exo_browser_mac.mm(342)] PlatformSetControl: 1 fr-1
[16965:24579:0711/054626:49762129424332:INFO:exo_frame_wrap.cc(322)] CreateCallback ExoFrameWrap
[16965:1291:0711/054626:49762130454517:INFO:exo_frame.cc(106)] ExoFrame SetType [0x798b2d80]: 1
[16965:1291:0711/054626:49762130498281:INFO:exo_frame.cc(97)] ExoFrame SetParent [0x7a39d600]: 0x799923e0
[16965:1291:0711/054626:49762130579353:INFO:exo_browser_mac.mm(342)] PlatformSetControl: 2 fr-2
[16965:1291:0711/054626:49762132797548:INFO:exo_browser_mac.mm(376)] PlatformSetControlDimension: 1 45
```

**Comment by spolu** [comment] 2014-07-11 17:09
Breach is highly unstable for now on Yosemite unfortunately :( You may want to rebuild it from Source to see if it fixes any of this ?

**Comment by naknut** [comment] 2014-07-12 16:53
It works in my MacBook with 10.10 installed.

**Comment by octalmage** [comment] 2014-07-12 20:37
I've never complied Chromium but I'll give it a go!

**Comment by spolu** [comment] 2014-07-12 20:38
Sweet: instructions here: https://github.com/breach/exo_browser/wiki/Building-the-ExoBrowser

**Comment by octalmage** [comment] 2014-07-13 01:12
Hmm, @naknut I wonder what's different then. Does Breach rely on anything external?

**Comment by derekbrown** [comment] 2014-07-16 04:24
I've rebuilt from local source and am getting this issue as well.

**Comment by spolu** [comment] 2014-07-16 15:15
Damn! You went through rebuilding the whole ExoBrowser?

**Comment by derekbrown** [comment] 2014-07-16 21:23
I used a freshly downloaded and installed ExoBrowser.app to run my local source from the command line. Didn't think I'd need to compile from source on OS/X.

**Comment by spolu** [comment] 2014-07-16 21:28
Yep, that's the thing this bug lies probably in the ExoBrowser... :)

**Comment by octalmage** [comment] 2014-07-17 12:59
I'll try this today. Wish me luck!

**Comment by brayniverse** [comment] 2014-07-17 14:09
Good luck :grinning:

**Comment by spolu** [comment] 2014-07-17 14:29
:+1:

**Comment by octalmage** [comment] 2014-07-17 18:08
Ok this may be a dumb question but where do I get gyp? Is it suppose to come with depot_tools?

**Comment by spolu** [comment] 2014-07-17 19:00
Yep!

**Comment by spolu** [comment] 2014-07-21 22:50
duplicate of #116

**Closed as completed by spolu** 2014-07-21 22:50 UTC
Labels: Duplicate
