### ISSUE TITLE
Page hangs when scrolling down

### ISSUE THREAD

**Issue by Tarang** [spolu/breach_core#63] opened 2014-07-10 19:56 UTC
On nearly all websites while scrolling down the page crashes (OS X 10.10).

**Comment by spolu** [comment] 2014-07-10 20:06
Yep we know it's not working well on Yosemite...

**Comment by Tarang** [comment] 2014-07-10 20:30
Just thought i'd mention it i didn't see it in the closed issues. I think it affects chrome too.

A really really exceptional piece of software btw!

**Comment by spolu** [comment] 2014-07-10 20:35
Thanks ;-)

**Comment by spolu** [comment] 2014-07-21 22:59
duplicate of #116

**Closed as completed by spolu** 2014-07-21 22:59 UTC
