### ISSUE TITLE
Some pages just give a blank screen when running under Yosemite

### ISSUE THREAD

**Issue by naknut** [spolu/breach_core#91] opened 2014-07-11 08:31 UTC
If i try to navigate to www.reddit.com or www.facebook.com I just get a blank screen. Is there any way to get some debug output so I can get an idea of what the problem is?

**Comment by omegahm** [comment] 2014-07-11 08:48
I had the same problem on Yosemite. I actually also tried exactly www.reddit.com and www.facebook.com. It works fine in Mavericks (10.9.4)

**Comment by naknut** [comment] 2014-07-11 08:58
Oooh, i use Yosemite aswell. So that seems to be the problem then. I updated the issue label to further express that this only happens in Yosemite.

**Comment by zhiayang** [comment] 2014-07-12 13:40
Additionally, some sites appear fine (http://www.youtube.com, http://forum.osdev.org), but again blank out once you scroll a little bit.

Also on Yosemite.

**Comment by spolu** [comment] 2014-07-21 22:52
duplicate of #116

**Closed as completed by spolu** 2014-07-21 22:52 UTC
