### ISSUE TITLE
[Windows] Creating working builds for Windows systems

### ISSUE THREAD

**Issue by Gwash3189** [spolu/breach_core#77] opened 2014-07-10 23:42 UTC
What exactly would it take for this to happen?
What is locking the alpha builds down to *nix systems?

**Comment by spolu** [comment] 2014-07-10 23:56
This requires a few additional C++ implemetation in the ExoBrowser layer to target Windows.
It might be easier to go directly for targeting Aura that is supported on both windows and linux now...

**Comment by spolu** [comment] 2014-07-21 22:56
duplicate of #90

**Closed as completed by spolu** 2014-07-21 22:56 UTC
